{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-image-availability-exporter.fullname" . }}
  labels:
    {{- include "k8s-image-availability-exporter.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: metrics
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: metrics
  selector:
    {{- include "k8s-image-availability-exporter.selectorLabels" . | nindent 4 }}
{{- end }}
